#!/usr/bin/env python3
"""
Copy figures and dependencies used by a LaTeX document.

Usage:
    python3 latex_deps.py <dep_file> <target_dir>

Arguments:
    dep_file    The dependency file (.dep) generated by the snapshot package.
    target_dir  The directory where dependencies will be copied.
"""

import os
import shutil
import sys

# File extensions to copy
EXTENSIONS = {
    'cls', 'pdf', 'pdf_tex', 'png', 'jpg', 'jpeg', 'bbl', 'bib', 'tex'
}

def main():
    print("--- Running Matteo Icardi's handy script: latex_deps.py ---")
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <dep_file> <target_dir>")
        sys.exit(1)

    dep_file = sys.argv[1]
    target_dir = sys.argv[2]

    print(f"Extracting all dependencies of '{dep_file}' and copying them to '{target_dir}'")

    if not os.path.isfile(dep_file):
        print(f"Error: .dep file '{dep_file}' does not exist.")
        print("Make sure you have \\RequirePackage{snapshot} at the beginning of your latex file.")
        sys.exit(1)

    if not os.path.exists(target_dir):
        try:
            os.makedirs(target_dir)
        except OSError as e:
            print(f"Error creating target directory: {e}")
            sys.exit(1)

    copy_dependencies(dep_file, target_dir)

def copy_dependencies(dep_file, target_dir):
    """Parses the .dep file and copies referenced files to the target directory."""
    try:
        with open(dep_file, 'r') as f:
            for line in f:
                if '*{file}' not in line:
                    continue
                
                # Parse the line to get the source file path
                # Format is usually: *{file} {path/to/file} {0000/00/00 v0.0} ...
                try:
                    parts = line.split('{')
                    if len(parts) < 3:
                        continue
                    source = parts[2].split('}')[0]
                except IndexError:
                    continue

                # Check extension
                _, ext = os.path.splitext(source)
                ext = ext.lower().lstrip('.')
                
                if ext not in EXTENSIONS:
                    continue
                
                print(f"Copying: {source}")
                try:
                    shutil.copy(source, target_dir)
                except OSError as e:
                    print(f"Warning: '{source}' could not be copied. Reason: {e}")

    except IOError as e:
        print(f"Error reading dependency file: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
